ignoreWorkspaceRootCheck: true

packages:
  - ./
  - cli
  - docs
  - playgrounds/nuxt
  - playgrounds/vue
  - playgrounds/repl

allowBuilds:
  '@parcel/watcher': false
  better-sqlite3: true
  esbuild: false
  puppeteer: true
  sharp: true
  simple-git-hooks: true
  vue-demi: false

overrides:
  '@types/node': 25.3.0
  h3: 1.15.11
  unplugin: 3.0.0
  unplugin-auto-import: 21.0.0
