export default {
  slots: {
    root: '',
    input: '',
    close: '',
    back: '',
    content: '',
    footer: '',
    viewport: '',
    group: '',
    empty: '',
    label: '',
    item: '',
    itemLeadingIcon: '',
    itemLeadingAvatar: '',
    itemLeadingAvatarSize: '',
    itemLeadingChip: '',
    itemLeadingChipSize: '',
    itemTrailing: '',
    itemTrailingIcon: '',
    itemTrailingHighlightedIcon: '',
    itemTrailingKbds: '',
    itemTrailingKbdsSize: '',
    itemWrapper: '',
    itemLabel: '',
    itemDescription: '',
    itemLabelBase: '',
    itemLabelPrefix: '',
    itemLabelSuffix: '',
  },
  variants: {
    virtualize: {
      true: {
        viewport: '',
      },
      false: {
        viewport: '',
      },
    },
    size: {
      xs: {
        input: '',
        empty: '',
        label: '',
        item: '',
        itemLeadingIcon: '',
        itemLeadingAvatarSize: '',
        itemLeadingChip: '',
        itemLeadingChipSize: '',
        itemTrailing: '',
        itemTrailingIcon: '',
        itemTrailingHighlightedIcon: '',
        itemTrailingKbds: '',
        itemTrailingKbdsSize: '',
      },
      sm: {
        input: '',
        empty: '',
        label: '',
        item: '',
        itemLeadingIcon: '',
        itemLeadingAvatarSize: '',
        itemLeadingChip: '',
        itemLeadingChipSize: '',
        itemTrailing: '',
        itemTrailingIcon: '',
        itemTrailingHighlightedIcon: '',
        itemTrailingKbds: '',
        itemTrailingKbdsSize: '',
      },
      md: {
        input: '',
        empty: '',
        label: '',
        item: '',
        itemLeadingIcon: '',
        itemLeadingAvatarSize: '',
        itemLeadingChip: '',
        itemLeadingChipSize: '',
        itemTrailing: '',
        itemTrailingIcon: '',
        itemTrailingHighlightedIcon: '',
        itemTrailingKbds: '',
        itemTrailingKbdsSize: '',
      },
      lg: {
        input: '',
        empty: '',
        label: '',
        item: '',
        itemLeadingIcon: '',
        itemLeadingAvatarSize: '',
        itemLeadingChip: '',
        itemLeadingChipSize: '',
        itemTrailing: '',
        itemTrailingIcon: '',
        itemTrailingHighlightedIcon: '',
        itemTrailingKbds: '',
        itemTrailingKbdsSize: '',
      },
      xl: {
        input: '',
        empty: '',
        label: '',
        item: '',
        itemLeadingIcon: '',
        itemLeadingAvatarSize: '',
        itemLeadingChip: '',
        itemLeadingChipSize: '',
        itemTrailing: '',
        itemTrailingIcon: '',
        itemTrailingHighlightedIcon: '',
        itemTrailingKbds: '',
        itemTrailingKbdsSize: '',
      },
    },
    active: {
      true: {
        item: '',
        itemLeadingIcon: '',
      },
      false: {
        item: '',
        itemLeadingIcon: '',
      },
    },
    loading: {
      true: {
        itemLeadingIcon: '',
      },
    },
  },

  defaultVariants: {
    size: 'md',
  },
};
